twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        category_repository: '@App\Repository\CategoryRepository'
        cart: '@App\Service\Cart'

when@test:
    twig:
        strict_variables: true
